// app/creator-terms/page.tsx
import Link from "next/link";
import { ArrowLeft, Wallet, Calendar, ShieldOff } from "lucide-react";

export const metadata = {
  title: "Creator Terms — TipaTale",
  description: "Terms every creator agrees to before receiving payouts on TipaTale.",
};

const SECTIONS = [
  { id: "acceptance", title: "Acceptance of these terms" },
  { id: "eligibility", title: "Eligibility" },
  { id: "earnings", title: "How earnings are calculated" },
  { id: "schedule", title: "Payment schedule" },
  { id: "methods", title: "Payout methods" },
  { id: "removed-books", title: "Removed or deleted books" },
  { id: "fraud", title: "Fraud, chargebacks, and disputes" },
  { id: "taxes", title: "Taxes" },
  { id: "holds", title: "Account holds" },
  { id: "changes", title: "Changes to these terms" },
  { id: "contact", title: "Questions" },
];

export default function CreatorTermsPage() {
  return (
    <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6">
      <Link
        href="/settings/payout"
        className="inline-flex items-center gap-1.5 font-sans text-sm font-medium text-ink-muted transition hover:text-ink"
      >
        <ArrowLeft size={15} /> Back to payout settings
      </Link>

      <div className="mt-6 border-b border-hairline pb-8">
        <span className="inline-flex items-center rounded-full bg-accent/10 px-2.5 py-1 font-sans text-xs font-semibold uppercase tracking-wide text-accent">
          Legal
        </span>
        <h1 className="mt-3 font-display text-3xl font-bold text-ink sm:text-4xl">Creator Terms</h1>
        <p className="mt-3 max-w-2xl font-sans text-sm leading-relaxed text-ink-muted">
          These are the terms every TipaTale creator agrees to before receiving coin-earning
          payouts. Read them once, then check back any time — they&apos;re always at this link.
        </p>
        <p className="mt-4 font-sans text-xs text-ink-muted">Last updated July 14, 2026</p>

        {/* Quick facts */}
        <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-3">
          <FactCard
            icon={<Wallet size={16} />}
            label="You keep"
            value="80%"
            detail="TipaTale takes a 20% platform commission"
          />
          <FactCard
            icon={<Calendar size={16} />}
            label="Paid out"
            value="Monthly"
            detail="Processed in the second week, for the prior month"
          />
          <FactCard
            icon={<ShieldOff size={16} />}
            label="Heads up"
            value="No refunds on takedowns"
            detail="Removed or deleted books forfeit unpaid earnings"
          />
        </div>
      </div>

      <div className="mt-8 grid grid-cols-1 gap-10 lg:grid-cols-[220px_1fr]">
        {/* Table of contents */}
        <nav aria-label="Table of contents" className="lg:sticky lg:top-10 lg:self-start">
          <p className="font-sans text-xs font-semibold uppercase tracking-wide text-ink-muted">On this page</p>
          <ul className="mt-3 flex flex-col gap-2 border-l border-hairline pl-3">
            {SECTIONS.map((s) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="font-sans text-sm text-ink-muted transition hover:text-accent"
                >
                  {s.title}
                </a>
              </li>
            ))}
          </ul>
        </nav>

        {/* Content */}
        <div className="flex flex-col gap-9">
          <Section id="acceptance" number="1" title="Acceptance of these terms">
            <p>
              These Creator Terms apply to any author who adds payout details to receive coin
              earnings on TipaTale. They sit alongside, and don&apos;t replace, our general Terms of
              Service. If the two conflict on payout matters, these Creator Terms control.
            </p>
          </Section>

          <Section id="eligibility" number="2" title="Eligibility">
            <p>
              You must be the verified owner of the payout account or wallet you add. Payout
              details must belong to you personally, or to a business you&apos;re authorized to
              receive funds on behalf of. We may ask for identity verification before releasing a
              payout, and may delay or withhold payment until that verification is complete.
            </p>
          </Section>

          <Section id="earnings" number="3" title="How earnings are calculated">
            <p>
              TipaTale takes a <strong className="text-ink">20% platform commission</strong> on
              coin earnings generated by your books. You keep the remaining{" "}
              <strong className="text-ink">80%</strong>. This split applies to reads, tips, and any
              other coin-based earning event on the platform, and is reflected in your earnings
              dashboard before payout.
            </p>
          </Section>

          <Section id="schedule" number="4" title="Payment schedule">
            <p>
              Payouts are processed once a month, during the{" "}
              <strong className="text-ink">second week of the month</strong>, covering earnings
              from the previous calendar month. Payouts aren&apos;t issued on a fixed calendar day
              — bank and network processing times vary, so funds may land a few business days
              after processing begins. We don&apos;t offer early or on-demand payouts outside this
              cycle.
            </p>
          </Section>

          <Section id="methods" number="5" title="Payout methods">
            <p>
              You can be paid to a Nigerian bank account (NUBAN) or to a supported crypto wallet.
              You&apos;re responsible for entering accurate details — we&apos;re not liable for
              funds sent to an incorrect account or wallet address you provided. Crypto payouts are
              sent on the network you select; sending to the wrong network can result in permanent
              loss of funds, and TipaTale cannot recover or reimburse misdirected crypto transfers.
            </p>
          </Section>

          <Section id="removed-books" number="6" title="Removed or deleted books">
            <p>
              If a book is deleted by you, or taken down by TipaTale for violating our content
              policies or Terms of Service, any unpaid earnings tied to that book are forfeited and
              will not be paid out. This applies whether the removal happens before or after the
              earnings would otherwise have been included in a payout cycle. Earnings already paid
              out prior to removal are not clawed back solely because the book was later removed,
              unless the removal was for fraud, plagiarism, or a chargeback-related violation.
            </p>
          </Section>

          <Section id="fraud" number="7" title="Fraud, chargebacks, and disputes">
            <p>
              If coins used to generate your earnings are later reversed — for example due to a
              payment dispute, chargeback, or fraudulent purchase — the corresponding amount may be
              deducted from your current balance or a future payout. Accounts found to be
              artificially inflating reads, tips, or engagement to generate payouts will have those
              earnings withheld and may be suspended.
            </p>
          </Section>

          <Section id="taxes" number="8" title="Taxes">
            <p>
              You&apos;re solely responsible for determining and meeting any tax obligations that
              apply to your earnings under the laws of your country or state. TipaTale doesn&apos;t
              withhold taxes on your behalf and doesn&apos;t provide tax advice.
            </p>
          </Section>

          <Section id="holds" number="9" title="Account holds">
            <p>
              We may place a temporary hold on a payout if we suspect fraud, if your payout details
              fail verification, or if your account is under review for a Terms of Service
              violation. We&apos;ll aim to resolve holds promptly and let you know what&apos;s
              needed to release them.
            </p>
          </Section>

          <Section id="changes" number="10" title="Changes to these terms">
            <p>
              We may update these Creator Terms from time to time, including the commission split
              or payment schedule. Material changes will be communicated in-app or by email before
              they take effect. Continuing to earn on TipaTale after a change takes effect means you
              accept the updated terms.
            </p>
          </Section>

          <Section id="contact" number="11" title="Questions">
            <p>
              If anything here is unclear, reach out to creator-support before adding your payout
              details — not after a payout has already been processed.
            </p>
          </Section>

          <div className="border-t border-hairline pt-6">
            <Link
              href="/settings/payout"
              className="inline-flex items-center gap-1.5 font-sans text-sm font-medium text-accent hover:underline"
            >
              <ArrowLeft size={15} /> Back to payout settings
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}

function FactCard({
  icon,
  label,
  value,
  detail,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  detail: string;
}) {
  return (
    <div className="rounded-xl border border-hairline bg-surface p-4">
      <div className="flex items-center gap-1.5 text-accent">
        {icon}
        <span className="font-sans text-xs font-semibold uppercase tracking-wide text-ink-muted">
          {label}
        </span>
      </div>
      <p className="mt-2 font-display text-lg font-bold text-ink">{value}</p>
      <p className="mt-0.5 font-sans text-xs leading-snug text-ink-muted">{detail}</p>
    </div>
  );
}

function Section({
  id,
  number,
  title,
  children,
}: {
  id: string;
  number: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section id={id} className="scroll-mt-10">
      <h2 className="font-display text-base font-semibold text-ink">
        <span className="text-ink-muted">{number}.</span> {title}
      </h2>
      <div className="mt-1.5 font-sans text-sm leading-relaxed text-ink-muted">{children}</div>
    </section>
  );
}