import type { Book, Author } from "@/app/types";

// Cover gradient combos — dark, rich, literary
export const COVER_GRADIENTS: Record<string, string> = {
  crimson:  "from-[#2a0808] to-[#6b1010]",
  navy:     "from-[#080d2a] to-[#101e60]",
  forest:   "from-[#081f08] to-[#104020]",
  umber:    "from-[#1f1005] to-[#5a2a08]",
  violet:   "from-[#120820] to-[#38105e]",
  slate:    "from-[#080e1f] to-[#121e38]",
  burgundy: "from-[#1f0510] to-[#5c0f28]",
  teal:     "from-[#041f1f] to-[#084040]",
  ochre:    "from-[#1a1205] to-[#503808]",
  charcoal: "from-[#0a0a0a] to-[#242424]",
  plum:     "from-[#180520] to-[#48105e]",
  bronze:   "from-[#1c1008] to-[#582e10]",
};

export const TRENDING_BOOKS: Book[] = [
  {
    id: "1",
    title: "The Ember Crown",
    author: "Lyra Ashvale",
    authorHandle: "lyra.writes",
    slug: "the-ember-crown",
    genre: "Fantasy",
    subGenre: "Dark Fantasy",
    coverGradient: COVER_GRADIENTS.crimson,
    coverEmoji: "🜲",
    rating: 4.9,
    reads: "2.4M",
    chapters: 47,
    status: "ongoing",
    isMature: true,
    badge: "Hot",
    synopsis:
      "Seraphine Vael was born without the ember-gift — the fire magic that marks every noble in the Ashen Kingdoms. In a world where the powerless are culled before their fifth winter, she has survived seventeen years on borrowed secrets. When the old king dies and the Ember Crown chooses no heir, Seraphine finds herself bound to an ancient trial designed not to crown her, but to unmake her.",
    tags: ["Enemies to lovers", "Dark magic", "Royalty", "Slow burn", "Chosen one"],
    accessType: "free",
    libraryCount: "312K",
  },
  {
    id: "2",
    title: "Blood & Borrowed Time",
    author: "Maren Cole",
    authorHandle: "marencole",
    slug: "blood-borrowed-time",
    genre: "Dark Fiction",
    coverGradient: COVER_GRADIENTS.burgundy,
    coverEmoji: "🗡",
    rating: 4.8,
    reads: "1.1M",
    chapters: 38,
    status: "completed",
    isMature: true,
    badge: "Hot",
    synopsis: "A pact made in blood. A debt collected in time itself.",
    tags: ["Dark", "Supernatural", "Completed"],
    accessType: "coins",
    libraryCount: "180K",
  },
  {
    id: "3",
    title: "Depth of the Pale Sea",
    author: "Soren Vayne",
    authorHandle: "sorenv",
    slug: "depth-of-the-pale-sea",
    genre: "Sci-Fi",
    coverGradient: COVER_GRADIENTS.navy,
    coverEmoji: "🌊",
    rating: 4.7,
    reads: "340K",
    chapters: 29,
    status: "ongoing",
    isMature: false,
    badge: "New",
    synopsis: "On a station at the edge of known space, a signal arrives that shouldn't exist.",
    tags: ["Space", "Mystery", "Thriller"],
    accessType: "free",
    libraryCount: "58K",
  },
  {
    id: "4",
    title: "Verdant Hollow",
    author: "Isla Thorne",
    authorHandle: "islawrites",
    slug: "verdant-hollow",
    genre: "Fantasy",
    coverGradient: COVER_GRADIENTS.forest,
    coverEmoji: "🌿",
    rating: 4.9,
    reads: "890K",
    chapters: 62,
    status: "ongoing",
    isMature: false,
    badge: "Hot",
    synopsis: "A forest that remembers. A girl the forest won't let leave.",
    tags: ["Epic Fantasy", "Nature magic", "Coming of age"],
    accessType: "free",
    libraryCount: "210K",
  },
  {
    id: "5",
    title: "The Alchemist's Daughter",
    author: "Cael Morrow",
    authorHandle: "caelmorrow",
    slug: "the-alchemists-daughter",
    genre: "Historical",
    coverGradient: COVER_GRADIENTS.umber,
    coverEmoji: "⚗️",
    rating: 4.6,
    reads: "520K",
    chapters: 44,
    status: "completed",
    isMature: false,
    badge: "Free",
    synopsis: "Prague, 1601. A secret buried in gold threatens to burn the empire down.",
    tags: ["Historical", "Alchemy", "Intrigue"],
    accessType: "free",
    libraryCount: "95K",
  },
  {
    id: "6",
    title: "What the Oracle Forgot",
    author: "Nira Sol",
    authorHandle: "nirasol",
    slug: "what-the-oracle-forgot",
    genre: "Fantasy",
    coverGradient: COVER_GRADIENTS.violet,
    coverEmoji: "🔮",
    rating: 4.8,
    reads: "78K",
    chapters: 14,
    status: "ongoing",
    isMature: false,
    badge: "New",
    synopsis: "She was built to see everything. Except the one thing that mattered.",
    tags: ["Prophecy", "Magic system", "Mystery"],
    accessType: "free",
    libraryCount: "12K",
  },
  {
    id: "7",
    title: "When Roses Learn to Lie",
    author: "Vera Ashby",
    authorHandle: "vera.ashby",
    slug: "when-roses-learn-to-lie",
    genre: "Romance",
    subGenre: "Dark Romance",
    coverGradient: COVER_GRADIENTS.burgundy,
    coverEmoji: "🥀",
    rating: 4.9,
    reads: "2.2M",
    chapters: 71,
    status: "completed",
    isMature: true,
    badge: "Hot",
    synopsis: "Love is just another word for surviving someone.",
    tags: ["Dark romance", "Slow burn", "Enemies to lovers"],
    accessType: "subscriber",
    libraryCount: "445K",
  },
  {
    id: "8",
    title: "Event Horizon Blues",
    author: "Dax Orion",
    authorHandle: "daxorion",
    slug: "event-horizon-blues",
    genre: "Sci-Fi",
    coverGradient: COVER_GRADIENTS.slate,
    coverEmoji: "🌌",
    rating: 4.5,
    reads: "210K",
    chapters: 33,
    status: "ongoing",
    isMature: false,
    badge: "Free",
    synopsis: "Jazz, black holes, and one very lost astronaut.",
    tags: ["Sci-Fi", "Literary", "Humor"],
    accessType: "free",
    libraryCount: "38K",
  },
  {
    id: "9",
    title: "The Tidebound Heir",
    author: "Kira Sable",
    authorHandle: "kirasable",
    slug: "the-tidebound-heir",
    genre: "Fantasy",
    coverGradient: COVER_GRADIENTS.teal,
    coverEmoji: "🐉",
    rating: 4.7,
    reads: "1.5M",
    chapters: 55,
    status: "ongoing",
    isMature: false,
    badge: "Hot",
    synopsis: "An heir bound to the tide must choose: her kingdom or the sea itself.",
    tags: ["Sea fantasy", "Political", "Dragons"],
    accessType: "free",
    libraryCount: "290K",
  },
  {
    id: "10",
    title: "The Hollow Season",
    author: "Mira Fenn",
    authorHandle: "mirafenn",
    slug: "the-hollow-season",
    genre: "Horror",
    coverGradient: COVER_GRADIENTS.charcoal,
    coverEmoji: "🕯",
    rating: 4.8,
    reads: "760K",
    chapters: 42,
    status: "completed",
    isMature: true,
    badge: "Complete",
    synopsis: "Every autumn the town forgets. This year, one girl refuses to.",
    tags: ["Horror", "Small town", "Memory"],
    accessType: "coins",
    libraryCount: "145K",
  },
  {
    id: "11",
    title: "Keys to the Undertow",
    author: "Sol Renner",
    authorHandle: "solrenner",
    slug: "keys-to-the-undertow",
    genre: "Mystery",
    coverGradient: COVER_GRADIENTS.plum,
    coverEmoji: "🗝",
    rating: 4.6,
    reads: "95K",
    chapters: 22,
    status: "ongoing",
    isMature: false,
    badge: "New",
    synopsis: "Seven locked doors. Six bodies. One detective who's already dead.",
    tags: ["Mystery", "Supernatural", "Detective"],
    accessType: "free",
    libraryCount: "18K",
  },
  {
    id: "12",
    title: "A War of Salted Iron",
    author: "Dane Harrow",
    authorHandle: "daneharrow",
    slug: "a-war-of-salted-iron",
    genre: "Fantasy",
    subGenre: "Epic Fantasy",
    coverGradient: COVER_GRADIENTS.bronze,
    coverEmoji: "⚔️",
    rating: 4.7,
    reads: "430K",
    chapters: 58,
    status: "ongoing",
    isMature: true,
    badge: "Hot",
    synopsis: "Two armies. One weapon neither side should have found.",
    tags: ["War", "Epic", "Magic system", "Grimdark"],
    accessType: "free",
    libraryCount: "98K",
  },
];

export const NEW_RELEASES: Book[] = [
  {
    id: "13",
    title: "Iron & Mourning",
    author: "Caius Blake",
    authorHandle: "caiusblake",
    slug: "iron-and-mourning",
    genre: "Fantasy",
    coverGradient: COVER_GRADIENTS.bronze,
    coverEmoji: "🛡",
    rating: 4.5,
    reads: "41K",
    chapters: 11,
    status: "ongoing",
    isMature: false,
    badge: "New",
    synopsis: "Grief given armour. A knight with nothing left to protect.",
    tags: ["Fantasy", "Grief", "War"],
    accessType: "free",
    libraryCount: "6K",
  },
  {
    id: "14",
    title: "Dusk & the Drowning",
    author: "Sable Rook",
    authorHandle: "sablerook",
    slug: "dusk-and-the-drowning",
    genre: "Dark Fiction",
    coverGradient: COVER_GRADIENTS.charcoal,
    coverEmoji: "🌑",
    rating: 4.4,
    reads: "29K",
    chapters: 9,
    status: "ongoing",
    isMature: true,
    badge: "New",
    synopsis: "The city drowns at midnight. She's the only one who notices.",
    tags: ["Dark", "Urban", "Supernatural"],
    accessType: "free",
    libraryCount: "4K",
  },
  {
    id: "15",
    title: "The Last Consul",
    author: "Petra Vane",
    authorHandle: "petravane",
    slug: "the-last-consul",
    genre: "Historical",
    coverGradient: COVER_GRADIENTS.ochre,
    coverEmoji: "📜",
    rating: 4.6,
    reads: "55K",
    chapters: 18,
    status: "ongoing",
    isMature: false,
    badge: "New",
    synopsis: "Rome's last honest man. History's shortest career.",
    tags: ["Rome", "Historical", "Political"],
    accessType: "free",
    libraryCount: "9K",
  },
  {
    id: "16",
    title: "A Debt in Red",
    author: "Vera Maris",
    authorHandle: "veramaris",
    slug: "a-debt-in-red",
    genre: "Romance",
    subGenre: "Dark Romance",
    coverGradient: COVER_GRADIENTS.crimson,
    coverEmoji: "🌹",
    rating: 4.7,
    reads: "88K",
    chapters: 16,
    status: "ongoing",
    isMature: true,
    badge: "New",
    synopsis: "He owns her debt. She intends to make him regret collecting.",
    tags: ["Dark romance", "Enemies to lovers", "Tension"],
    accessType: "free",
    libraryCount: "16K",
  },
  {
    id: "17",
    title: "Synthetic Hearts",
    author: "Nira Sol",
    authorHandle: "nirasol",
    slug: "synthetic-hearts",
    genre: "Sci-Fi",
    subGenre: "Sci-Fi Romance",
    coverGradient: COVER_GRADIENTS.navy,
    coverEmoji: "🤖",
    rating: 4.8,
    reads: "130K",
    chapters: 20,
    status: "ongoing",
    isMature: false,
    badge: "New",
    synopsis: "They were built to feel nothing. Then they met each other.",
    tags: ["Sci-Fi", "Romance", "AI"],
    accessType: "free",
    libraryCount: "22K",
  },
  {
    id: "18",
    title: "The Cartographer's Lie",
    author: "Petra Vane",
    authorHandle: "petravane",
    slug: "the-cartographers-lie",
    genre: "Fantasy",
    coverGradient: COVER_GRADIENTS.ochre,
    coverEmoji: "🗺",
    rating: 4.5,
    reads: "180K",
    chapters: 36,
    status: "completed",
    isMature: false,
    badge: "Complete",
    synopsis: "Every map she drew was a lie. One of them created a country.",
    tags: ["Fantasy", "Historical", "Adventure"],
    accessType: "free",
    libraryCount: "34K",
  },
];

export const DARK_FICTION_SHELF: Book[] = [
  TRENDING_BOOKS[9],  // The Hollow Season
  TRENDING_BOOKS[6],  // When Roses Learn to Lie
  TRENDING_BOOKS[1],  // Blood & Borrowed Time
  TRENDING_BOOKS[11], // A War of Salted Iron
];

export const FANTASY_SHELF: Book[] = [
  TRENDING_BOOKS[0],  // The Ember Crown
  TRENDING_BOOKS[3],  // Verdant Hollow
  TRENDING_BOOKS[8],  // The Tidebound Heir
  TRENDING_BOOKS[11], // A War of Salted Iron
];

export const FEATURED_AUTHORS: Author[] = [
  {
    id: "1",
    name: "Lyra Ashvale",
    handle: "@lyra.writes",
    initials: "LA",
    coverGradient: COVER_GRADIENTS.crimson,
    followers: "42.1K",
    genres: ["Dark Fantasy", "Romance"],
    quote: "I write the stories I was told didn't have an audience.",
    bookCount: 8,
  },
  {
    id: "2",
    name: "Isla Thorne",
    handle: "@islawrites",
    initials: "IT",
    coverGradient: COVER_GRADIENTS.forest,
    followers: "61.4K",
    genres: ["Epic Fantasy", "Literary"],
    quote: "Every forest has a door. I find them.",
    bookCount: 5,
  },
  {
    id: "3",
    name: "Vera Ashby",
    handle: "@vera.ashby",
    initials: "VA",
    coverGradient: COVER_GRADIENTS.burgundy,
    followers: "89.2K",
    genres: ["Dark Romance", "Fantasy"],
    quote: "Love is just another word for surviving someone.",
    bookCount: 12,
  },
  {
    id: "4",
    name: "Soren Vayne",
    handle: "@sorenv",
    initials: "SV",
    coverGradient: COVER_GRADIENTS.navy,
    followers: "28.6K",
    genres: ["Sci-Fi", "Thriller"],
    quote: "The sea never stops moving. Neither should a sentence.",
    bookCount: 6,
  },
];

export const GENRES = [
  "All", "Fantasy", "Dark Fiction", "Romance",
  "Thriller", "Sci-Fi", "Historical", "Mystery",
  "Horror", "Literary", "Young Adult",
];

export const CONTINUE_READING = {
  book: TRENDING_BOOKS[0],
  chapter: 22,
  chapterTitle: "The Glass Meridian",
  progressPct: 63,
  minutesLeft: 18,
};